export const FETCH_USER_ACTIVE = 'FETCH_USER_ACTIVE';
export const FETCH_USER_LIST = 'FETCH_USER_LIST';
export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE';

export const STORE_USER_DATA = 'STORE_USER_DATA';


export const UPDATE_USER_LIST = 'UPDATE_USER_LIST';